name: OpenDart Executive Purchase Monitor


env:
  TZ: Asia/Seoul  # 한국 시간대 설정

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas pytz

    - name: Run OpenDart monitoring
      env:
        DART_API_KEY: ${{ secrets.DART_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python main.py

    - name: Upload logs and results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: monitoring-logs-${{ github.run_number }}
        path: |
          *.log
          *.json
        retention-days: 30
